### ISSUE TITLE
Support systemd

### ISSUE THREAD

**Issue by acrisci** [matisku/ansible-teamcity-agent#4]
Hi,

Right now, the role tries to put the service directly into /etc/init but newer distros have mostly moved to systemd which uses systemd unit files instead of init scripts. The role fails in this case.

I think there is a fact called `service_mgr` which is set to `systemd` when systemd is used for starting services.

This would require a template for a systemd unit file to be used in place of the init script.

Are you interested in this change?

**Comment by matisku** [comment]
Hello,

Thank for the you input.
Tests looks good so I'll merge your pull request.
